# Generated by Django 2.2 on 2020-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_auto_20201005_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/8/88/Danny_DeVito_cropped_and_edited_for_brightness.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='portfolio_image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/8/88/Danny_DeVito_cropped_and_edited_for_brightness.jpg', max_length=500),
        ),
    ]
